# Header

menu:
  主页: /
  随笔: /tags/life

# SubNav
subnav:
  github: "#" weibo: "#" rss: "#"
  #zhihu: "#"
  #douban: "#"
  #mail: "#"
  #facebook: "#"
  #google: "#"
  #twitter: "#"
  #linkedin: "#"

rss: /atom.xml

# 是否需要修改 root 路径
# 如果您的网站存放在子目录中，例如 http://yoursite.com/blog，
# 请将您的 url 设为 http://yoursite.com/blog 并把 root 设为 /blog/。
root: 

# Content
excerpt_link: more
fancybox: true
mathjax: false

# 是否开启动画效果
animate: true

# 是否在新窗口打开链接
open_in_new: false

# Miscellaneous
google_analytics: ''
favicon: /favicon.jpg

#你的头像url
avatar: /images/xumeng.jpg

#是否开启分享
share_jia: true
share_addthis: false

#是否开启多说评论，填写你在多说申请的项目名称 duoshuo: duoshuo-key
#若使用disqus，请在博客config文件中填写disqus_shortname，并关闭多说评论
duoshuo: false

# 如不需要，将该项置为false
# 比如
#smart_menu:
#  friends: false

smart_menu:
  innerArchive: '所有文章'
  tagcloud: '标签'
  friends: false
  aboutme: '关于我'

friends:
    google: https:www.google.com/

aboutme: 大部分人在二三十岁上就死去了，因为过了这个年龄，他们只是自己的影子，伺候的雨声则是在模仿自己种度过，日复一日，更机械，更装腔作势地重复他们在有生之年的所作所为，所思所想，所爱所爱恨
